spring.application.name=MediSlot

spring.datasource.url = jdbc:postgresql://localhost:5432/medislot
spring.datasource.username =your_username
spring.datasource.password = your_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
